### ISSUE TITLE
Support for Elonics E4000 tuner

### ISSUE THREAD

**Issue by wfrisby** [google/radioreceiver#1]
# Support for Elonics E4000 tuner is missing.

The app finds the USB receiver but I get the following error:
`There was a problem: USB write failed (value 0x34 index 0x610 data [0x0]), rc=4, lastErrorMessage="Transfer stalled."`

I believe that the register values for configuring the R820T tuner are different from the E4000 tuner.

USB device paramters:
Realtek Semiconductor Corp. RTL2838 DVB-T
VendorId: 0x0bda
ProductId: 0x2838

I'm willing to add support for the E4000 but I'm not sure how difficult it will be. If you could give me an estimate where to start that would be great!

**Comment by jtarrio** [comment]
Yes, Radio Receiver does not support the E4000, only the R820T.

Both chips are completely different, so implementing the E4000 would be quite involved, and frankly I don't think it's worth the effort since devices with the R820T chip are so much cheaper and easier to find (to the point that many that are advertised as "E4000" actually have an R820T).

**Comment by wfrisby** [comment]
Bummer.

So, I just ordered the R820T2 for $14.99. Much better use of my time... I'll have to see how it compares to the E4000 when it arrives.

Anyways, this is an awesome project!

**Comment by jtarrio** [comment]
I also ordered one today, so if anything, support for R820T2 will improve in the future :)
